config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies do
	collection do
  		get 'search'
  	end
  end
  root 'movies#index'
  get 'pages/about'
  get 'pages/media'
  get 'pages/faq'
  get 'pages/privacy'
  get 'pages/contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	mount_uploader :image, ImageUploader
	##searchkick
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:search, :index, :show]
  # GET /movies
  # GET /movies.json

  def search
    if params[:search].present?
      @movies = Movie.search(params[:search])
    else
      @movies = Movie.all
    end
  end


  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :image, :description, :genre, :year)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def media
  end

  def faq
  end

  def privacy
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_bootstrap.html.erb
  <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

   <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

app/views/layouts/_carousel.html.erb
 <header class="showcase">
        <div class="showcase-top">
            <img src="img/logo.png" alt="Netflix">
        
            <li><%= link_to "Sign in", new_user_session_path, class: "btn btn-rounded"%></li>

        </div>
        <div class="showcase-content">
            <h1>See what's next</h1>
            <p>Watch anywhere. Cancel anytime.</p>
            <a href="#" class="btn btn-xl">
                Try 30 Days free<i class="fas fa fa-chevron-right btn-icon"></i>
            </a>

        </div>

    </header>

    <section class="tabs">
        <div class="container">
            <div id="tab-1" class="tab-item tab-border">
                <i class="fas fa fa-download fa-3x"></i>
                <p class="hide-sm">Cancel Anytime</p>
            </div>

            <div id="tab-2" class="tab-item">
                <i class="fas fa fa-mobile-phone fa-3x"></i>
                <p class="hide-sm"> Watch Anywhere</p>
            </div>

            <div id="tab-3" class="tab-item">
                <i class="fas fa fa-tags fa-3x"></i>
                <p class="hide-sm">Pick your price</p>
            </div>
        </div>
    </section>
    <section class="tab-content">
        <div class="container">
            <!-- Tab 1 Content -->
            <div id="tab-1-content" class="tab-content-item show">
                <div class="tab-1-content-inner">
                    <div>
                        <p class="text-lg">
                            If you decide Netflix isn't for you - no problem. No commitment.
                            Cancel online anytime.
                        </p>

                        <a href="#" class="btn btn-lg">Watch Free For 30 Days</a>
                    </div>
                    <img src="img/tab-content-1.png" alt="">
                </div>
            </div>

            <!-- Tab 2 Content -->

            <div id="tab-2-content" class="tab-content-item">
                <div class="tab-2-content-top">
                    <p class="text-lg">
                        Watch TV shows and movies anytime, anywhere - personlized for you.
                    </p>
                    <a href="#" class="btn btn-lg">Watch Free For 30 Days</a>
                </div>
                <div class="div tab-2-content-bottom">
                    <div>
                        <img src="img/tab-content-2-1.png" alt="">
                        <p class="text=md">Watch on your TV</p>
                        <p class="text-dark">Smart TV's Playstations, Xbox, Chromecast, Apple TV, Blu-ray players and
                            more.</p>
                    </div>

                    <div>
                        <img src="img/tab-content-2-2.png" alt="">
                        <p class="text-md">Watch instantly or download for later</p>
                        <p class="text-dark">Available on phone and tablet. wherever you go.</p>
                    </div>

                    <div>
                        <img src="img/tab-content-2-3.png" alt="">
                        <p class="text-md">Use any computer</p>
                        <p class="text-dark">Watch right on Netflix.com/p>
                    </div>

                </div>
            </div>

            <!-- Tab 3 Content -->
            <div id="tab-3-content" class="tab-content-item">
                <div class="text-center">
                    <p class="text-lg">
                        Choose one plan and watch everything on Netflix
                    </p>
                    <a href="#" class="btn btn-lg">Watch Free For 30 days</a>
                </div>

                <table class="table table-borderless table-hover table-striped table-dark">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Basic</th>
                            <th>Standard</th>
                            <th>Premium</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Monthly price after free month ends on 6/19/19</td>
                            <td>$8.99</td>
                            <td>12.99</td>
                            <td>$15.99</td>
                        </tr>
                        <tr>
                            <td>HD Available</td>
                            <td><i class="fas fa fa-times"></i></td>
                            <td><i class="fas fa fa-check"></i></td>
                            <td><i class="fas fa fa-check"></i></td>
                        </tr>
                        <tr>
                            <td>Ultra HD Available</td>
                            <td><i class="fas fa fa-times"></i></td>
                            <td><i class="fas fa fa-check"></i></td>
                            <td><i class="fas fa fa-check"></i></td>
                        </tr>
                        <tr>
                            <td>Screen you can watch on at any time</td>
                            <td>1</td>
                            <td>2</td>
                            <td>4</td>
                        </tr>
                        <tr>
                            <td>Watch on your laptop, TV, phone and tablet</td>
                            <td><i class="fas fa fa-times"></i></td>
                            <td><i class="fas fa fa-check"></i></td>
                            <td><i class="fas fa fa-check"></i></td>
                        </tr>
                        <tr>
                            <td>Unlimited movies and TV shows</td>
                            <td><i class="fas fa fa-times"></i></td>
                            <td><i class="fas fa fa-check"></i></td>
                            <td><i class="fas fa fa-check"></i></td>
                        </tr>
                        <tr>
                            <td>Cancel anytime</td>
                            <td><i class="fas fa fa-times"></i></td>
                            <td><i class="fas fa fa-check"></i></td>
                            <td><i class="fas fa fa-check"></i></td>
                        </tr>
                        <tr>
                            <td>First month free</td>
                            <td><i class="fas fa fa-times"></i></td>
                            <td><i class="fas fa fa-check"></i></td>
                            <td><i class="fas fa fa-check"></i></td>
                        </tr>
                    </tbody>

                </table>
            </div>
        </div>
    </section>

app/views/layouts/_footer.html.erb
<footer class="footer">
        <p>Questions? Call 1-866-579-7172</p>
        <div class="footer-cols">
            <ul>
                <li><a href="/pages/faq">FAQ</a></li>
                <li><a href="#">Investor Relations</a></li>
                <li><a href="#">Ways To Watch</a></li>
                <li><a href="#">Corporate Information</a></li>
                <li><a href="#">Netflix Originals</a></li>
            </ul>
            <ul>
                <li><a href="#">Help Center</a></li>
                <li><a href="#">Jobs</a></li>
                <li><a href="#">Terms of Use</a></li>
                <li><a href="#">Contact Us</a></li>
            </ul>
            <ul>
                <li><a href="/users/sign_in">Account</a></li>
                <li><a href="#">Redeem Gift Cards</a></li>
                <li><a href="/pages/privacy">Privacy</a></li>
                <li><a href="#">Speed Test</a></li>
            </ul>
            <ul>
                <li><a href="/pages/media">Media Center</a></li>
                <li><a href="#">Buy Gift Cards</a></li>
                <li><a href="#">Cookie Preferences</a></li>
                <li><a href="#">Corporate Information</a></li>
                <li><a href="#">Legal Notices</a></li>
            </ul>

        </div>
</footer>
<div class="center">
<p>This is under the MIT license, only for learning and contribution purposes.</p>
</div>

app/views/layouts/_front.html.erb
 <header class="showcase">
        <div class="showcase-top">
            <img src="img/logo.png" alt="Netflix Logo">
             <li><%= link_to "Sign in", new_user_session_path, class: "btn btn-rounded"%></li>
        </div>
        <div class="showcase-content">
            <h1>Unlimited movies, TV shows and more.</h1>
            <h3>Watch anywhere. Cancel anytime.</h3>
            <p>Ready to watch? Enter your email to create or restart your membership.</p>
            <div class="field">
                <input type="email" name="email" id="mail" placeholder="Email address">
                <div class ="ap">
                  <a href="/users/sign_up" class="btn btn-rounded my-2 my-sm-0 center">  GET STARTED ></a>
                </div>
            </div>
        </div>
    </header>
    <section class="style-cards">


        <div class="card-1">
            <div class="desc-1">
                <h1>Enjoy on your TV.</h1>
                <h3>Watch on smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blue-ray players and more.</h3>
            </div>
            <img src="img/tv.png" alt="Netflix TV">
            <video class="video-1" autoplay="" playsinline="" muted="" loop="">
                <source src="img/video-tv-0819.m4v" type="video/mp4"></video>
        </div>
        <div class="card-2">
            <img src="img/mobile-0819.jpg" alt="Netflix Mobile">
            <div class="desc-2">
                <h1>Download your shows to watch offline.</h1>
                <h3>Save your favorites easily and always have something to watch.</h3>
            </div>
        </div>
        <div class="card-3">
            <div class="desc-3">
                <h1>Watch everywhere.</h1>
                <h3>Stream unlimited movies and TV shows on your phone, tablet, laptop, and TV without paying more.</h3>
            </div>
            <img src="img/device-pile.png" alt="Device-Pile-In">
            <video class="video-2" autoplay="" playsinline="" muted="" loop="">
                <source src="img/video-devices.m4v" type="video/mp4"></video>
        </div>

    </section>

    <section class="lastsection">
        <div class="faq">
            <h1>Frequently Asked Questions</h1>
            <ul class="questions">
                <li>What is Netflix</li>
                <li>How much does Netflix cost?</li>
                <li>Where can I watch?</li>
                <li>How do I cancel?</li>
                <li>What can I watch on netflix?</li>
                <li>Is Netflix good for kids?</li>
            </ul>
            <p>Ready to watch? Enter your email to create or restart your membership.</p>
            <div class="input">
                <input type="email" name="email" placeholder="Email Address">
                <a href="/users/sign_up" class="btn btn-rounded my-2 my-sm-0 center"><button>GET STARTED ></button></a>
            </div>
        </div>
    </section>
  

app/views/layouts/_modal.html.erb
    
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>


<div class="text-center">
  <!-- Button HTML (to Trigger Modal) -->
  <a href="#myModal" class="trigger-btn" data-toggle="modal">Click to Open Login Modal</a>
</div>

<!-- Modal HTML -->
<div id="myModal" class="modal fade">
  <div class="modal-dialog modal-login">
    <div class="modal-content">
      <div class="modal-header">        
        <h4 class="modal-title">Sign In</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <form action="/examples/actions/confirmation.php" method="post">
          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-user"></i></span>
              <input type="text" class="form-control" name="username" placeholder="Username" required="required">
            </div>
          </div>
          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon"><i class="fa fa-lock"></i></span>
              <input type="text" class="form-control" name="password" placeholder="Password" required="required">
            </div>
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block btn-lg">Sign In</button>
          </div>
          <p class="hint-text"><a href="#">Forgot Password?</a></p>
        </form>
      </div>
      <div class="modal-footer">Don't have an account? <a href="#">Create one</a></div>
    </div>
  </div>
</div> 

app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<a href="/"><img src="/assets/logo.png" alt="Netflix"></a>
          
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              
              <li class="nav-item"><%= link_to "About", pages_about_path, class: "nav-link" %></li>

              <li class="nav-item"><%= link_to "Media", pages_media_path, class: "nav-link"%></li>

              <li class="nav-item"><%= link_to "Privacy", pages_privacy_path, class: "nav-link" %></li>

              <li class="nav-item"><%= link_to "FAQ", pages_faq_path, class: "nav-link"%></li>

               <li class="nav-item"><%= link_to "Contact", pages_contact_path, class: "nav-link"%></li>
              
               <%= form_tag search_movies_path, method: :get, class: "form-inline my-2 my-lg-0" do%>
          <p>
            <%= text_field_tag :search, params[:search], class: "form-control mr-sm-2" %>
            <%= submit_tag "Search", name:nil, class: "btn btn-outline-secondary my-2 my-sm-0"%>
          </p>
          <% end %>            
              

            </ul>
              
        
          <ul class="navbar-nav navbar-right">
           <% if user_signed_in? %>
               <li class="nav-item"><%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link"%></li> 
              <li class="nav-item"><%= link_to "Sign out", destroy_user_session_path, class: "nav-link", method: :delete %></li>

              <% else %>
              <li class="nav-item"><%= link_to "Sign up", new_user_registration_path, class: "nav-link" %></li>
           
             <li class="nav-item"><%= link_to "Sign in", new_user_session_path, class: "btn btn-primary"%></li>

             <% end %>
         
          </ul>

          </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Netflix - Watch TV Shows Online, Watch Movies Online</title>
    <%= render 'layouts/bootstrap'%>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if request.original_url != root_url %>
    <%= render 'layouts/navbar' %>
    <% end %>

<% if request.original_url == root_url %>
<%= render 'layouts/front' %>    
  
<% end %>

    <div class="container-fluid">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>

    
    <%= yield %>
  
     <%= render 'layouts/footer' %>
    </div>

        <script src="js/main.js"></script>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true, :html => {multipart: true}) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :genre %>
    <%= form.text_field :genre, class: "form-control" %>
  </div>

  <div class="form-control">
    <%= form.label :year %>
    <%= form.date_select :year, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Movies</h3>


<table class="table table-borderless table-striped table-dark table-hover table-condensed">
  <thead>
    <tr>
      <th>Title</th>
     
      <th>Description</th>
      <th>Genre</th>
      <th>Year</th>
      <% if user_signed_in? %>
      <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.title, movie %></td>
    
        <td><%= movie.description %></td>
        <td><%= movie.genre %></td>
        <td><%= movie.year %></td>
        <td><%= link_to 'Show', movie %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_movie_path(movie), class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Movie', new_movie_path %>
<% end %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/search.html.erb
<h1>Search:\></h1>

<table class="table table-borderless table-striped table-dark table-hover table-condensed">
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Description</th>
      <th>Genre</th>
	    <th>Year</th>
      <% if user_signed_in? %>
      <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.image %></td>
        <td><%= movie.description %></td>
        <td><%= movie.genre %></td>
        <td><%= movie.year %></td>
        <td><%= link_to 'Show', movie %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-3">

      <p>
        <strong>Title:</strong>
        <%= @movie.title %>
      </p>

      <p>
        <strong>Image:</strong>
        <%= image_tag @movie.image_url %>
      </p>
  </div>

  <div class="col-md-9">
      <p>
        <strong>Description:</strong>
        <%= @movie.description %>
      </p>

      <p>
        <strong>Genre:</strong>
        <%= @movie.genre %>
      </p>

      <p>
        <strong>Year:</strong>
        <%= @movie.year %>
      </p>

  </div>
</div>
<% if user_signed_in? %>
<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>
<% end %>

app/views/pages/about.html.erb
<h1>Welcome to NETFLIX</h1>
<h2>This is one of the sample applications from <%= link_to "personal tutorial exercises", "http://www.baserails.com" %></h2>

app/views/pages/contact.html.erb
<h1>We would love to hear from you</h1>
<p>Contact us @ cybtech127@gmail.com</p>

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/pages/media.html.erb
<h1>Pages#media</h1>
<p>Find me in app/views/pages/media.html.erb</p>

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>